const crypto = require('node:crypto');
const InterviewQuestionBank = require('../models/interviewQuestionBank');
const {
  normalizeComparableText,
  normalizeQuestionText,
  normalizeAnswerText,
  sanitizeDifficulty,
  sanitizeTags
} = require('../services/interviewQuestionQualityService');

const DEFAULT_SORT = {
  usageCount: -1,
  confidenceScore: -1,
  popularity: -1,
  lastUsedAt: -1,
  createdAt: -1
};
const MIN_APPROVED_CONFIDENCE = 0.72;
const MIN_APPROVED_RELEVANCE = 0.75;
const MIN_TOP_CONFIDENCE = 0.78;
const MIN_TOP_RELEVANCE = 0.78;
const VALID_SOURCES = new Set(['verified_seed', 'prebuilt', 'ai', 'ai_generated', 'scraped', 'user_asked']);
const VALID_CATEGORIES = new Set(['conceptual', 'scenario_based', 'code_output', 'best_practice', 'system_design', 'behavioral']);
const SOURCE_PRIORITY = {
  verified_seed: 4,
  prebuilt: 4,
  ai_generated: 3,
  user_asked: 3,
  ai: 2,
  scraped: 1
};
const NOISY_CONTENT_REGEX = /(generated by ai during triage|parent related to #\d+|what to build|PRODUCT\.md|DESIGN\.md|stocked-equipment|issue should produce|pull request|stop winging it|for mid-to-senior developers)/i;
const toQuestionHash = (value = '') => crypto
  .createHash('sha256')
  .update(normalizeComparableText(value))
  .digest('hex');

const compareQuestionPriority = (left, right) => {
  const sourceDelta = (SOURCE_PRIORITY[right.sourceType] || 0) - (SOURCE_PRIORITY[left.sourceType] || 0);
  if (sourceDelta !== 0) return sourceDelta;
  if (Number(right.qualityScore || 0) !== Number(left.qualityScore || 0)) return Number(right.qualityScore || 0) - Number(left.qualityScore || 0);
  if (Number(right.usageCount || 0) !== Number(left.usageCount || 0)) return Number(right.usageCount || 0) - Number(left.usageCount || 0);
  if (Number(right.confidenceScore || 0) !== Number(left.confidenceScore || 0)) return Number(right.confidenceScore || 0) - Number(left.confidenceScore || 0);
  if (Number(right.relevanceScore || 0) !== Number(left.relevanceScore || 0)) return Number(right.relevanceScore || 0) - Number(left.relevanceScore || 0);
  if (Number(right.popularity || 0) !== Number(left.popularity || 0)) return Number(right.popularity || 0) - Number(left.popularity || 0);
  return new Date(right.createdAt || 0).getTime() - new Date(left.createdAt || 0).getTime();
};

const normalizeSourceType = (value = '') => {
  const normalized = String(value || '').trim().toLowerCase();
  if (normalized === 'prebuilt') return 'verified_seed';
  if (VALID_SOURCES.has(normalized)) return normalized;
  return 'ai_generated';
};

const approvedQualityCriteria = (minConfidence = MIN_APPROVED_CONFIDENCE, minRelevance = MIN_APPROVED_RELEVANCE) => ([
  { qualityState: { $ne: 'rejected' } },
  {
    $or: [
      { qualityStatus: 'approved' },
      { qualityStatus: { $exists: false } },
      { qualityStatus: '' }
    ]
  },
  { isApproved: { $ne: false } },
  { confidenceScore: { $gte: minConfidence } },
  { question: { $not: NOISY_CONTENT_REGEX } },
  { answer: { $not: NOISY_CONTENT_REGEX } },
  {
    $or: [
      { relevanceScore: { $gte: minRelevance } },
      { relevanceScore: { $exists: false } }
    ]
  }
]);

const buildQuestionFilter = ({ topicKey = '', skill = '', topicType = '', difficulty = '', tags = '', query = '', excludeGenericSeeds = false } = {}) => {
  const filter = {
    $and: approvedQualityCriteria()
  };
  const normalizedTopicKey = String(topicKey || '').trim().toLowerCase();
  const normalizedSkill = String(skill || '').trim().toLowerCase();
  const normalizedTopicType = String(topicType || '').trim().toLowerCase();
  const normalizedTags = String(tags || '').trim().toLowerCase();
  const normalizedQuery = String(query || '').trim();

  if (normalizedTopicKey) {
    filter.topicKey = normalizedTopicKey;
  } else if (normalizedSkill) {
    filter.skill = normalizedSkill;
  }

  if (normalizedTopicType) {
    filter.topicType = normalizedTopicType;
  }

  const normalizedDifficulty = String(difficulty || '').trim().toLowerCase();
  if (normalizedDifficulty) {
    filter.difficulty = normalizedDifficulty;
  }

  if (normalizedTags) {
    const tagList = normalizedTags
      .split(',')
      .map((tag) => String(tag || '').trim().toLowerCase())
      .filter(Boolean);

    if (tagList.length > 0) {
      filter.tags = { $in: tagList };
    }
  }

  if (normalizedQuery) {
    filter.$text = { $search: normalizedQuery };
  }

  if (excludeGenericSeeds) {
    filter['sourceMeta.seedVersion'] = { $ne: 'v2' };
  }

  return filter;
};

const findQuestionsPage = async ({ filter = {}, page = 1, limit = 20, includeTextScore = false } = {}) => {
  const skip = (Math.max(1, page) - 1) * Math.max(1, limit);

  const projection = includeTextScore
    ? { score: { $meta: 'textScore' } }
    : undefined;

  const sort = includeTextScore
    ? { score: { $meta: 'textScore' }, usageCount: -1, confidenceScore: -1, popularity: -1, createdAt: -1 }
    : DEFAULT_SORT;

  const [questions, total] = await Promise.all([
    InterviewQuestionBank.find(filter, projection).sort(sort).skip(skip).limit(limit).lean(),
    InterviewQuestionBank.countDocuments(filter)
  ]);

  return { questions, total };
};

const upsertQuestions = async (records = []) => {
  if (!Array.isArray(records) || records.length === 0) {
    return { insertedCount: 0, upsertedIds: [] };
  }

  const operations = records.map((record) => {
    const topicKey = String(record.topicKey || record.skill || '').trim().toLowerCase();
    const normalizedQuestion = normalizeComparableText(record.normalizedQuestion || record.question);
    const normalizedQuestionHash = String(record.normalizedQuestionHash || toQuestionHash(normalizedQuestion)).trim().toLowerCase();
    const normalizedAnswer = normalizeComparableText(record.normalizedAnswer || record.answer);
    const rawSourceType = String(record.sourceType || record.source || 'verified_seed').trim().toLowerCase();
    const sourceType = normalizeSourceType(rawSourceType);
    const category = String(record.category || 'conceptual').trim().toLowerCase();
    const answerSections = record.answerSections && typeof record.answerSections === 'object'
      ? record.answerSections
      : {};
    const hasStructuredAnswer = Object.keys(answerSections).length > 0 || record.answerFormat === 'structured';
    const normalizedSkill = String(record.skill || topicKey || '').trim().toLowerCase();
    const rawQualityStatus = String(record.qualityStatus || record.qualityState || 'approved').trim().toLowerCase();
    const qualityStatus = rawQualityStatus === 'review' ? 'pending' : rawQualityStatus;
    const confidenceScore = Number(record.confidenceScore || 0.7);

    return {
      updateOne: {
        filter: {
          topicKey,
          $or: [
            { normalizedQuestionHash },
            { normalizedQuestion }
          ]
        },
        update: {
          $setOnInsert: {
            usageCount: Number(record.usageCount || 0),
            lastUsedAt: record.lastUsedAt || null,
            createdAt: record.createdAt || new Date()
          },
          $set: {
            topicKey,
            topicType: String(record.topicType || '').trim().toLowerCase() || 'technology',
            skill: normalizedSkill,
            question: normalizeQuestionText(record.question),
            answer: normalizeAnswerText(record.answer),
            answerSections,
            normalizedQuestion,
            normalizedQuestionHash,
            normalizedAnswer,
            difficulty: sanitizeDifficulty(record.difficulty),
            tags: sanitizeTags(record.tags || []),
            source: sourceType === 'user_asked' ? 'ai_generated' : sourceType,
            sourceType,
            sourceMeta: record.sourceMeta || {},
            confidenceScore,
            relevanceScore: Number(record.relevanceScore || Math.min(0.95, Math.max(0.75, confidenceScore))),
            category: VALID_CATEGORIES.has(category) ? category : 'conceptual',
            qualityScore: Math.min(5, Math.max(1, Number(record.qualityScore || 3))),
            answerFormat: hasStructuredAnswer ? 'structured' : 'plain',
            isEnriched: Boolean(record.isEnriched || hasStructuredAnswer),
            qualityState: String(record.qualityState || 'approved').trim().toLowerCase(),
            isApproved: record.isApproved !== false,
            qualityStatus,
            rejectedReason: String(record.rejectedReason || '').trim(),
            popularity: Number(record.popularity || 0),
            topicDimensions: record.topicDimensions || {}
          }
        },
        upsert: true
      }
    };
  });

  const result = await InterviewQuestionBank.bulkWrite(operations, { ordered: false });
  return {
    insertedCount: Number(result.upsertedCount || 0),
    upsertedIds: Object.values(result.upsertedIds || {})
  };
};

const findTopQuestions = async ({ topicKey = '', limit = 30, difficulty = '', tags = '' } = {}) => {
  const filter = buildQuestionFilter({
    topicKey,
    difficulty,
    tags,
    excludeGenericSeeds: true
  });
  filter.qualityScore = { $gte: 4 };
  filter.$and = [
    ...(filter.$and || []),
    ...approvedQualityCriteria(MIN_TOP_CONFIDENCE, MIN_TOP_RELEVANCE)
  ];

  const rows = await InterviewQuestionBank.find(filter)
    .sort({ usageCount: -1, qualityScore: -1, confidenceScore: -1, relevanceScore: -1, popularity: -1, lastUsedAt: -1, createdAt: -1 })
    .limit(Math.min(120, Math.max(30, Number(limit || 30) * 4)))
    .lean();

  return rows
    .sort(compareQuestionPriority)
    .slice(0, Math.min(30, Math.max(1, Number(limit || 30))));
};

const findApprovedQuestionsByNormalizedQuestions = async ({ topicKey = '', normalizedQuestions = [] } = {}) => {
  const normalizedTopicKey = String(topicKey || '').trim().toLowerCase();
  const safeQuestions = Array.isArray(normalizedQuestions)
    ? normalizedQuestions.map((value) => String(value || '').trim().toLowerCase()).filter(Boolean)
    : [];

  if (!normalizedTopicKey || safeQuestions.length === 0) return [];

  return InterviewQuestionBank.find({
    topicKey: normalizedTopicKey,
    normalizedQuestion: { $in: safeQuestions },
    $and: approvedQualityCriteria()
  }).lean();
};

const findAllQuestionsPage = async ({ topicKey = '', page = 1, limit = 10, difficulty = '', tags = '', category = '', source = '' } = {}) => {
  const filter = buildQuestionFilter({ topicKey, difficulty, tags, excludeGenericSeeds: true });
  const normalizedCategory = String(category || '').trim().toLowerCase();
  const normalizedSource = String(source || '').trim().toLowerCase();
  if (normalizedCategory) filter.category = normalizedCategory;
  if (normalizedSource) {
    if (normalizedSource === 'ai') filter.sourceType = { $in: ['ai', 'ai_generated', 'user_asked'] };
    else if (normalizedSource === 'seed') filter.sourceType = { $in: ['verified_seed', 'prebuilt'] };
    else if (normalizedSource !== 'database') filter.sourceType = normalizedSource;
  }

  const pageSize = Math.max(1, Number(limit || 10));
  const currentPage = Math.max(1, Number(page || 1));
  const skip = (currentPage - 1) * pageSize;
  const [rows, total] = await Promise.all([
    InterviewQuestionBank.find(filter)
      .sort({ qualityScore: -1, usageCount: -1, confidenceScore: -1, relevanceScore: -1, popularity: -1, createdAt: -1 })
      .limit(500)
      .lean(),
    InterviewQuestionBank.countDocuments(filter)
  ]);

  const questions = rows
    .sort(compareQuestionPriority)
    .slice(skip, skip + pageSize);

  return { questions, total };
};

const findSearchTextMatches = async ({ topicKey = '', query = '', limit = 5, difficulty = '', tags = '' } = {}) => {
  const filter = buildQuestionFilter({
    topicKey,
    difficulty,
    tags,
    query,
    excludeGenericSeeds: true
  });

  return InterviewQuestionBank.find(filter, { score: { $meta: 'textScore' } })
    .sort({ score: { $meta: 'textScore' }, qualityScore: -1, usageCount: -1, confidenceScore: -1 })
    .limit(Math.max(1, Number(limit || 5)))
    .lean();
};

const findAiGeneratedByTopic = async ({ topicKey = '', topic = '', limit = 10 } = {}) => {
  const normalizedTopicKey = String(topicKey || '').trim().toLowerCase();
  const normalizedTopic = String(topic || '').trim().toLowerCase();
  const filter = {
    topicKey: normalizedTopicKey,
    sourceType: { $in: ['ai', 'ai_generated', 'user_asked'] },
    $and: approvedQualityCriteria()
  };
  if (normalizedTopic) {
    filter.$or = [
      { tags: normalizedTopic },
      { question: new RegExp(normalizedTopic.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') },
      { 'sourceMeta.topic': normalizedTopic }
    ];
  }

  return InterviewQuestionBank.find(filter)
    .sort({ qualityScore: -1, usageCount: -1, confidenceScore: -1, createdAt: -1 })
    .limit(Math.max(1, Number(limit || 10)))
    .lean();
};

const countAiGeneratedByTopic = async ({ topicKey = '', topic = '' } = {}) => {
  const normalizedTopicKey = String(topicKey || '').trim().toLowerCase();
  const normalizedTopic = String(topic || '').trim().toLowerCase();
  const filter = {
    topicKey: normalizedTopicKey,
    sourceType: { $in: ['ai', 'ai_generated', 'user_asked'] },
    $and: approvedQualityCriteria()
  };
  if (normalizedTopic) {
    filter.$or = [
      { tags: normalizedTopic },
      { 'sourceMeta.topic': normalizedTopic },
      { 'sourceMeta.query': normalizedTopic }
    ];
  }
  return InterviewQuestionBank.countDocuments(filter);
};

const findNeedsEnrichment = async ({ limit = 50 } = {}) => (
  InterviewQuestionBank.find({
    $or: [
      { category: { $exists: false } },
      { isEnriched: false },
      { answerFormat: { $ne: 'structured' } }
    ]
  })
    .sort({ createdAt: 1 })
    .limit(Math.max(1, Number(limit || 50)))
);

const updateQuestionById = async (id, update = {}) => {
  if (!id) return null;
  return InterviewQuestionBank.findByIdAndUpdate(id, update, { new: true }).lean();
};

const findExactReusableQuestion = async ({ topicKey = '', question = '', minConfidence = 0.55 } = {}) => {
  const normalizedQuestion = normalizeComparableText(question);
  if (!normalizedQuestion) return null;

  return InterviewQuestionBank.findOne({
    topicKey: String(topicKey || '').trim().toLowerCase(),
    $and: approvedQualityCriteria(minConfidence, MIN_APPROVED_RELEVANCE),
    $or: [
      { normalizedQuestionHash: toQuestionHash(normalizedQuestion) },
      { normalizedQuestion }
    ]
  }).lean();
};

const findSemanticCandidates = async ({ topicKey = '', tags = [], limit = 40, minConfidence = 0.6 } = {}) => {
  const filter = {
    topicKey: String(topicKey || '').trim().toLowerCase(),
    $and: approvedQualityCriteria(minConfidence, MIN_APPROVED_RELEVANCE)
  };
  const safeTags = sanitizeTags(tags);
  if (safeTags.length) filter.tags = { $in: safeTags };

  return InterviewQuestionBank.find(filter)
    .sort({ relevanceScore: -1, confidenceScore: -1, usageCount: -1, popularity: -1, createdAt: -1 })
    .limit(limit)
    .lean();
};

const incrementQuestionUsage = async (id) => {
  if (!id) return;
  await InterviewQuestionBank.updateOne(
    { _id: id },
    { $inc: { usageCount: 1 }, $set: { lastUsedAt: new Date() } }
  );
};

const fetchComparableQuestionsByTopic = async (topicKey = '', limit = 500) => {
  if (!topicKey) return [];
  const rows = await InterviewQuestionBank.find({ topicKey: String(topicKey).toLowerCase() })
    .select('normalizedQuestion question')
    .limit(limit)
    .lean();

  return rows
    .map((item) => item.normalizedQuestion || normalizeComparableText(item.question))
    .filter(Boolean);
};

const getSourceMixByTopic = async (topicKey = '') => {
  if (!topicKey) return {};

  const rows = await InterviewQuestionBank.aggregate([
    {
      $match: {
        topicKey: String(topicKey || '').trim().toLowerCase()
      }
    },
    {
      $group: {
        _id: { $ifNull: ['$sourceType', '$source'] },
        count: { $sum: 1 }
      }
    }
  ]);

  return rows.reduce((acc, row) => {
    acc[String(row._id || 'unknown')] = Number(row.count || 0);
    return acc;
  }, {});
};

const incrementUsageStats = async (ids = []) => {
  const normalizedIds = Array.isArray(ids) ? ids.filter(Boolean) : [];
  if (normalizedIds.length === 0) return;

  await InterviewQuestionBank.updateMany(
    { _id: { $in: normalizedIds } },
    {
      $inc: { usageCount: 1 },
      $set: { lastUsedAt: new Date() }
    }
  );
};

const countQuestionsByTopic = async (topicKey = '') => {
  if (!topicKey) return 0;
  return InterviewQuestionBank.countDocuments({
    topicKey: String(topicKey || '').trim().toLowerCase(),
    $and: approvedQualityCriteria()
  });
};

const countQuestionsByTopicAndSeedVersion = async (topicKey = '', seedVersion = '') => {
  if (!topicKey || !seedVersion) return 0;
  return InterviewQuestionBank.countDocuments({
    topicKey: String(topicKey || '').trim().toLowerCase(),
    'sourceMeta.seedVersion': seedVersion,
    qualityState: { $ne: 'rejected' },
    isApproved: { $ne: false }
  });
};

module.exports = {
  buildQuestionFilter,
  findQuestionsPage,
  findTopQuestions,
  findApprovedQuestionsByNormalizedQuestions,
  findAllQuestionsPage,
  findSearchTextMatches,
  findAiGeneratedByTopic,
  countAiGeneratedByTopic,
  findNeedsEnrichment,
  updateQuestionById,
  upsertQuestions,
  findExactReusableQuestion,
  findSemanticCandidates,
  fetchComparableQuestionsByTopic,
  getSourceMixByTopic,
  incrementUsageStats,
  incrementQuestionUsage,
  toQuestionHash,
  countQuestionsByTopic,
  countQuestionsByTopicAndSeedVersion,
  normalizeSourceType
};
